Fix comtypes cast() error - use POINTER for IPropertyStore
Error: 'cast() argument 2 must be a pointer type'

Fixed by importing POINTER from comtypes and wrapping IPropertyStore:
- cast(obj, IPropertyStore) -> cast(obj, POINTER(IPropertyStore))

This was preventing get_all_recording_devices() from working,
which is why VB-CABLE couldn't be detected.